version: '3.8'

services:
  fastapi:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    networks:
      - mynetwork
    environment:
      - FASTAPI_ENV=production

  redis:
    image: redis:latest
    networks:
      - mynetwork

  mongo:
    image: mongo:latest
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
